### ISSUE TITLE
ARC compatibility

### ISSUE THREAD

**Issue by ghost** [D-Nice/nbaser#6]
Hello! I was testing some Nimble packages with ARC, and found out that your package fails tests with ARC. It turned out that the cause is simple - you're relying in `repr` which behaves differently for ARC.

I suggest you to consider not using repr at all (since it's really only for humans and isn't supposed to be parsed programmatically), or at least fix it for ARC (and ORC which will probably become the default in 1.4), the simplest possible fix being:
```nim
      runedAlphabet.repr[0 .. ^(when defined(gcArc): 1 else: 2)].split("@".runeAtPos(0), 1)[1] &
```
on line 314 in `nbaser.nim`

**Comment by ghost** [comment]
Also, for your `benchmark` on my machine I get (on latest devel):

- With refc:
```
starting benchmarks...

base58 16 bytes
  encode 596582 ops/s
  decode 464489 ops/s

base58 32 bytes
  encode 230403 ops/s
  decode 167990 ops/s

base58 48 bytes
  encode 102269 ops/s
  decode 75548 ops/s

base2 16 bytes
  encode 155998 ops/s
  decode 59417 ops/s

base2 32 bytes
  encode 37231 ops/s
  decode 15301 ops/s

base2 48 bytes
  encode 18397 ops/s
  decode 6548 ops/s

base256 16 bytes
  encode 355600 ops/s
  decode 251026 ops/s

base256 32 bytes
  encode 211023 ops/s
  decode 127719 ops/s

base256 48 bytes
  encode 112436 ops/s
  decode 67044 ops/s
```

- With ARC:
```
base58 16 bytes
  encode 645240 ops/s
  decode 482034 ops/s

base58 32 bytes
  encode 240311 ops/s
  decode 177707 ops/s

base58 48 bytes
  encode 107229 ops/s
  decode 80917 ops/s

base2 16 bytes
  encode 167000 ops/s
  decode 38953 ops/s

base2 32 bytes
  encode 44853 ops/s
  decode 9672 ops/s

base2 48 bytes
  encode 18984 ops/s
  decode 3981 ops/s

base256 16 bytes
  encode 503980 ops/s
  decode 218229 ops/s

base256 32 bytes
  encode 253162 ops/s
  decode 82129 ops/s

base256 48 bytes
  encode 126374 ops/s
  decode 39983 ops/s
```

- With markAndSweep:
```
starting benchmarks...

base58 16 bytes
  encode 700775 ops/s
  decode 485953 ops/s

base58 32 bytes
  encode 248539 ops/s
  decode 170524 ops/s

base58 48 bytes
  encode 109741 ops/s
  decode 76669 ops/s

base2 16 bytes
  encode 170799 ops/s
  decode 62527 ops/s

base2 32 bytes
  encode 45535 ops/s
  decode 15782 ops/s

base2 48 bytes
  encode 19227 ops/s
  decode 6732 ops/s

base256 16 bytes
  encode 419505 ops/s
  decode 262777 ops/s

base256 32 bytes
  encode 229405 ops/s
  decode 130927 ops/s

base256 48 bytes
  encode 120128 ops/s
  decode 70006 ops/s
```

just for the reference.
And ARC is fully deterministic unlike other Nim GC's :)

**Comment by D-Nice** [comment]
Thanks for this info and your work @Yardanico 

I had also tried ARC at various stages of its development with the benchmark as well, but didn't wish to tailor this package for it yet, since it still was quite WIP at the time.

I'll take a look into making it ready for ARC :)

**Comment by D-Nice** [comment]
The above commit fixes this, I'll look to merge this and increment version soon.

I'm mainly using 1.2.2 Nim stable, and in that version, ARC was broken, specifically sequtils.insert is broken and zeroes out the complete sequence when used, rendering decode useless. I have tested with devel and all seems to be good now.

**Comment by ghost** [comment]
> The above commit fixes this, I'll look to merge this and increment version soon.
> 
> I'm mainly using 1.2.2 Nim stable, and in that version, ARC was broken, specifically sequtils.insert is broken and zeroes out the complete sequence when used, rendering decode useless. I have tested with devel and all seems to be good now.

Thanks :) wonder why did you use converters though - they're don't need to be used when your proc is for converting something, their main purpose is _implicit_ conversions which you don't seem to do.

**Comment by D-Nice** [comment]
Just a preference for explicitness that the proc's sole purpose is conversion. You're right that in my case I'm not utilizing the main idea behind it which is for implicit conversion, but I have seen this pattern used by others and have chosen to follow it. If it is an anti-pattern to do so, let me know. 

And regardless thanks for the heads up and inquiry about it!

**Comment by ghost** [comment]
@D-Nice well one problem might be that this converter will be called implicitly where you wouldn't expect it to be, and honestly I didn't see that pattern used by others, but it's fine I guess :)

**Comment by D-Nice** [comment]
Fair enough, if it leaves room for such issues that may occur it may indeed be better to get rid off.

I could make the excuse of continuing to use it by setting the line to:

```nim
  $(uchar.uint32)
```

albeit I'm unsure how to do similar with `seq[uint32]`, if you do know, would be good to know going forward.

However, going down this path, is likely one of just needless overengineering on my end, since in this case, each proc (converter in my case) are called only once, it likely makes more sense to just directly inline the casts into the code.

**Comment by ghost** [comment]
@D-Nice well, first of all, `cast[uint32](uchar)` and `uint32(uchar)` are different things - first one is a cast (like `reinterpret_cast` in C++, so it can be pretty unsafe), second is a conversion (which is safe). For uchar itself your approach will work just fine, yes, for seq[uchar] you just do the same loop you did before, something like:
```nim
# assuming we have a runedAlphabet seq
var myUints = newSeq[uint32](runedAlphabet.len)
for i, elem in runedAlphabet:
  myUints[i] = elem.uint32
```

**Comment by D-Nice** [comment]
@Yardanico I'm sufficiently satisfied with https://github.com/D-Nice/nbaser/pull/7, if you do have any further feedback feel free to chime in there.

Thanks again.

**Comment by ghost** [comment]
@D-Nice no, it's all fine, thanks for fixing everything :)
